# Generated by Django 3.2.7 on 2021-09-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('daily_rate', models.FloatField()),
                ('director', models.CharField(max_length=255)),
                ('rate', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG13', 'PG-13'), ('NC17', 'NC-17')], default='G', max_length=4)),
                ('genres', models.ManyToManyField(to='movie.Genre')),
            ],
        ),
    ]
